name: Main

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  devops-vars:
    uses: VirdocsSoftware/github-actions/.github/workflows/devops-vars.yml@998114aaca6eb57d38ec82cd08385116e6e2d2bf

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your reposit      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello world!

  dev-deploy:
    runs-on: ubuntu-latest
    needs: [build, devops-vars]
    if: ${{ needs.devops-vars.outputs.DEVOPS_IS_ENV_DEV == 'true' }}
    env:
      STACK_NAME: my-stack-${{ needs.devops-vars.outputs.DEVOPS_BRANCH_ENV_NAME }}
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying stack ${{ env.STACK_NAME }}
