name: Pull Request Teardown

on:
  pull_request:
    types: [closed]

jobs:
  devops-vars:
    uses: VirdocsSoftware/github-actions/.github/workflows/devops-vars.yml@186d1b43377be7160f3809153f275cc44ef21c85

  # Deletes branch deployment...
  delete-branch-deployment:
    runs-on: ubuntu-latest
    needs: [devops-vars]
    env:
      STACK_NAME: my-stack-${{ needs.devops-vars.outputs.DEVOPS_BRANCH_ENV_NAME }}
    steps:
      - name: Delete Branch Deployment
        run: echo Deleting stack ${{ env.STACK_NAME }}
